---
apiVersion: v1
kind: Namespace
metadata: 
  name: fortune-ns
  labels: 
    app: fortune
    version: v1
    cost-center: backend

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortune-deploy
  namespace: fortune-ns
  labels:
    app: fortune

spec:
  replicas: 3
  selector:
    matchLabels:
      app: fortune-pod
  template:
    metadata:
      name: fortune-pod
      labels:
        app: fortune-pod
    spec: 
      containers:
      - name: fortune-container
        image: chukmunnlee/fortune:v1
        imagePullPolicy: IfNotPresent
        ports:
        - name: fort-port
          containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: fortune-svc
  namespace: fortune-ns
  labels:
    app: fortune

spec:
  type: LoadBalancer
  selector: 
    app: fortune-pod
  ports: 
  - name: fort-svc-port
    port: 80
    targetPort: 3000
    