---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortune-deploy
  labels:
    app: fortune

spec:
  replicas: 3
  selector:
    matchLabels:
      app: fortune-pod
  template:
    metadata:
      name: fortune-pod
      labels:
        app: fortune-pod
    spec: 
      containers:
      - name: fortune-container
        image: chukmunnlee/fortune:v1
        imagePullPolicy: IfNotPresent
        ports:
        - name: fort-port
          containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: fortune-svc
  #namespace: fortune-ns
  labels:
    app: fortune

spec:
  #type: LoadBalancer
  type: ClusterIP
  selector: 
    app: fortune-pod
  ports: 
  - name: fort-svc-port
    port: 3000
    targetPort: fort-port
    
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: fortune-ing
  labels:
    app: fortune

spec:
  rules:
  - host: fortune.157.230.193.198.nip.io
    http:
      paths:
      - path: /
        backend:
          serviceName: fortune-svc
          servicePort: fort-svc-port