---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: wp-pvc
  labels:
    app: wordpress
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage
  volumeMode: Filesystem