--- 
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: wp-hpa
  labels: 
    app: wordpress

spec:
  minReplicas: 1
  maxReplicas: 4

  behavior:
    scaleDown:
      policies:
        - periodSeconds: 60
          type: Pods
          value: 1

    scaleUp:
      policies:
        - periodSeconds: 30
          type: Pods
          value: 1

  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: wp-deploy

  metrics:
  - type: Resource
    resource: 
      name: cpu
      target:
        type: Utilization
        averageUtilization: 15

  - type: Resource
    resource: 
      name: memory
      target:
        type: Utilization
        averageUtilization: 80